### ISSUE TITLE
イラスト作成

### ISSUE THREAD

**Issue by rensanrenren** [furuhashilab/V-F_OnlineHackathon_Nov#5]

**Comment by Babby168** [comment]
##  メンバーキャラ作成
以前作成したふるはしくんのタッチを基にその他V＆Fメンバーのキャラを作成。

### ＜途中報告＞
* 青木と馬場が似過ぎてるので、馬場にキャップを被せる。
* はがは現在制作途中なので暫しお待ちを。
* 独断と偏見で身体の色を定めていきます。
（馬場と青木の色は現状ので固定）

<img width="1440" alt="スクリーンショット 2021-10-31 15 04 14" src="https://user-images.githubusercontent.com/40033443/139570334-e9e87512-8557-42e3-bf0f-8994d1834602.png">

**Comment by Natsumi917** [comment]
はが途中経過
・「ハッカソンに追われています」スタンプ
・「データが消えた」スタンプ　を作成
![無題5_20211031204537](https://user-images.githubusercontent.com/67300697/139585873-1b27dad6-2812-411e-b85a-1f24d60c37c6.PNG)
![無題6_20211031213541](https://user-images.githubusercontent.com/67300697/139585880-896d6c42-1491-4bfe-b56b-ef39cf62cd79.PNG)

**Comment by Babby168** [comment]
ちょっとはがちゃんが似てなさ過ぎ問題がありますが、一旦これで通したいと思う所存でございます。。w


<img width="416" alt="スクリーンショット 2021-11-01 2 59 58" src="https://user-images.githubusercontent.com/40033443/139596038-85ba32c2-2b89-482f-a60a-75ab5771f616.png">

ちなみに、
はがちゃんのインスタより、成人式の写真で紫を着用してたので、胴体カラーを紫にしてみたところ、
見た目の年齢が倍増して見えてしまったので、妥当にピンクでいかせていただきます、、w

<img width="235" alt="スクリーンショット 2021-11-01 2 51 54" src="https://user-images.githubusercontent.com/40033443/139595764-f4878079-9403-4929-8d4c-b629a6e41af8.png">


<img width="294" alt="スクリーンショット 2021-11-01 2 53 16" src="https://user-images.githubusercontent.com/40033443/139595810-e7e001a4-df98-4575-9c3b-c0083e0a3bd4.png">

**Comment by Babby168** [comment]
上のやつのPDFファイル一応置いときます。

[hackathon-LINE_STAMP-01.pdf](https://github.com/furuhashilab/V-F_OnlineHackathon_Nov/files/7449438/hackathon-LINE_STAMP-01.pdf)

**Comment by rensanrenren** [comment]
いいっすね

**Comment by Natsumi917** [comment]
追加です。最終的に上２つと合わせて６個です。
デカくてすみません！
![無題5_20211102000752](https://user-images.githubusercontent.com/67300697/139699558-09979b8d-3ae3-4229-934f-86cff15bc334.PNG)
![無題7_20211102000841](https://user-images.githubusercontent.com/67300697/139699572-cc5f8236-0b56-4c75-9948-f5498fb8cdd0.PNG)
![無題8_20211102002711](https://user-images.githubusercontent.com/67300697/139699576-b4b5063d-f874-4054-9929-2a4f90692f2c.PNG)
![無題10_20211102003623](https://user-images.githubusercontent.com/67300697/139699577-f90b58ea-cd98-4de8-acab-aad56343ed93.PNG)

**Comment by rensanrenren** [comment]
かわええ！
