### ISSUE TITLE
デザイン案提案

### ISSUE THREAD

**Issue by rensanrenren** [furuhashilab/V-F_OnlineHackathon_Nov#6]
* [ ] 「グラレコ誰がやる？」スタンプ
* [ ] 「ハッカソンに追われてる」スタンプ
* [ ] 「データ消えた」スタンプ
* [ ] 「aftereffect難しい」スタンプ
* [ ] メンバーの顔スタンプ
* [ ] 動画制作で使えるような擬音系の素材
* [ ] 再生ボタン等の動画系の絵と日常使いできるスタンプ
<img src = "https://user-images.githubusercontent.com/49857703/139204650-ab41618f-f997-4b9d-b338-412f933094f4.jpeg" width = "200">

こういう系
<img src = "https://user-images.githubusercontent.com/49857703/139205180-4060f325-d914-4e14-a557-a20dce8f2173.PNG" width = "200">

- 擬音系素材例
<img src = "https://user-images.githubusercontent.com/49857703/139244545-7bcce21a-7481-4415-a8d2-50a57dac8fdb.png" width = "200">

**Comment by Babby168** [comment]
* ふるはしくんキャラクター、たしかうちが作ったキャラだったからVFで出しちゃわね！？っていう案
![ふるはしくん](https://user-images.githubusercontent.com/40033443/139377747-7691ce0b-f61f-4bc4-99cd-b51273acf7eb.png)

**Comment by Babby168** [comment]
* 「静かに！！今撮影中！」のスタンプ
* 「完成〜！」スタンプ
* 「どこでやる？」スタンプ
* 「いいね！」スタンプ
* 「これオフレコね」スタンプ

**Comment by Babby168** [comment]
ロゴもどっかで使いたい

**Comment by Natsumi917** [comment]
擬音かボタン系をVFのロゴカラーで作りたいです

**Comment by Natsumi917** [comment]
デザイン案大きく分けて
→擬音素材、再生ボタン系、メンバー顔、「〇〇」系

・擬音：どの擬音にするか(1~3種類)
→れんさんオススメあります？

・ボタン：「再生・ストップ」か「音量の大と消音」のペアがよさげ、、
→どう思います？あと色をVFカラーとか、、

・メンバー顔：４人分＋古橋先生
→ バビさん顔とか書くの得意ですか？

・「〇〇」系：絵柄と文字的なやつ or 文字だけ？
→ バビさんメンバーの顔かこっちメイン(2~3?)とどっちがいいですか？葉賀と分担しましょ

**Comment by rensanrenren** [comment]
> ・擬音：どの擬音にするか(1~3種類)
→れんさんオススメあります？

↓このサイトみたいな感じとか？
[マンガ文字素材dddFont](https://dddfont.com/)
